category_field = '> Тег/Категория'
start_date_field = '> Начальная дата'
end_date_field = '> Конечная дата'
description_field = '> Описание'
elapsing_field = '> Продолжительность'
work_value = 'работа'